language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
before_install:
- sudo apt-get -qq update
- sudo apt install -y libusb-1.0-0-dev libudev-dev python-dev
script: make test
deploy:
  provider: pypi
  user: BarnabyShearer
  on:
    tags: true
  password:
    secure: d7ioIJW00Z0ghvuqoOh3X4Ai1sJkuJ492FqRq83CcCiB2TnxkNeNCF0fRBqD1ZSPlXrgbfBBG3lyc1d6/O24Qe2JMMmVBq0de+r7xL7G48AzFLOaIcwMixHw1YgTTGkcTP4DljlncimEMUb4L1JUGA7dSCHTLqLc2Wd061gKj9UlZ/Qx8nI6jx/IV9CJttHjQzDEP4PgoGCz59tj+E4nqevw3s9oCQOFdIpOpHzE1z694WH/s+0ZTb10HXxVy8t6o2zI3S3EzB9Wsy72tQ2g025v4Nzkf3eMUFhQ0IWti+L2ULYMS01z22Hpr7vGt2obTvodnNpqG9kx8leSQeDP5hxlxjJ0pbH9uLOD9p++QFgMwmRkxKUj0Dd0N/d+Fpf9cdNNnnrD5OfTM+vyabNvib/2uOsIlAyv/XzCNnMLQR8B2hJbJOkK0z26zU1rTpGwxtlWbdmK3CrE7H+8S/QrTyrSPJqtA+HQD1y9PkyLfdpcwF5pB8QkSIVsYgmySta2ZFWQc/QeEkOU5Pl5IZ09sVEcdQw4+khsIDQwUN9QKoE8ptZafyCpr+QY7lwDdBGOaM4zxEHTut6R8z2Skx14l0QuQVfnnh9qe+eCzCXsoo/XUxMTm9eHBaCBSuahtaP/zaSJ8aULNr0Zt9+EuCEf2GT4ztzNkra4766a8WZZdew=
